version: 2.1

jobs:
  build-and-test:
    - image: circleci/python:3.7.1
    steps:
      - run: pip install -r requirements.txt
      - run:
          command: calculo.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
